<?php

declare(strict_types=1);

namespace App\Platform\Routing\Generator;

use App\Platform\Routing\RouteEntry;

final readonly class RoutesWriter
{
    /**
     * @param RouteProvider $provider Routes provider
     * @param string $outputFile Path to the routes configuration file
     */
    public function __construct(
        private RouteProvider $provider,
        private string $outputFile,
    ) {}

    public function generateRoutesFile(): void
    {
        $routes = $this->provider->getRoutes();
        $content = $this->generateFileContent($routes);

        file_put_contents($this->outputFile, $content);
    }

    /**
     * @param list<RouteEntry> $routes
     */
    private function generateFileContent(array $routes): string
    {
        $routesCode = [];
        $imports = [
            'App\Platform\Http\Handler\HandlerInterface',
        ];

        foreach ($routes as $route) {
            $handlerClass = $route->handler;
            $imports[] = $handlerClass;
            $handlerShortName = substr($handlerClass, strrpos($handlerClass, '\\') + 1);

            $comment = $route->operationId !== null ? "    // {$route->operationId}\n" : '';
            $routesCode[] = "{$comment}    [
        'method' => '{$route->method}',
        'path' => '{$route->path}',
        'handler' => {$handlerShortName}::class,
    ],";
        }

        $routesStr = implode("\n", $routesCode);

        // Remove duplicates and sort imports
        $imports = array_unique($imports);
        sort($imports);

        // Generate use statements
        $useStatements = array_map(static fn($class) => "use {$class};", $imports);
        $useStatementsStr = implode("\n", $useStatements);

        return <<<PHP
            <?php

            declare(strict_types=1);

            {$useStatementsStr}

            /**
             * WARNING: This file is automatically generated
             * from protobuf definitions. Do not edit manually.
             *
             * @return array<array{
             *     method: string,
             *     path: string,
             *     handler: class-string<HandlerInterface>
             * }>
             */
            return [
            {$routesStr}
            ];

            PHP;
    }
}
