version: '3'

server:
  command: "php index.php"

http:
  address: 0.0.0.0:8080
  pool:
    allocate_timeout: 10s
    num_workers: 5

rpc:
  listen: tcp://127.0.0.1:6001

# do not use development mode in production
logs:
  level: debug
  mode: development

status:
  address: 127.0.0.1:2114
