version: '3'

vars:
  PROTO_DIR: protos/proto
  SDK_GEN_DIR: protos/gen
  DOCS_GEN_DIR: docs
  PHP: php
  COMPOSER: composer

tasks:
  install:
    cmd: "{{.COMPOSER}} install"
    sources:
      - composer.json
    generates:
      - vendor/autoload.php

  var:
    cmd: mkdir -p var
    status:
      - test -d var
    silent: true
    internal: true

  fixcs:
    deps: [ var, install ]
    cmds:
      - "PHP_CS_FIXER_IGNORE_ENV=true {{.PHP}} vendor/bin/php-cs-fixer fix --verbose {{.CLI_ARGS}}"

  lint:
    cmds:
      - task: fixcs
        vars:
          CLI_ARGS: "--dry-run {{.CLI_ARGS}}"

  verify:
    deps: [ var, install, phpstan, test ]

  phpstan:
    deps: [ var, install ]
    cmds:
      - "{{.PHP}} vendor/bin/phpstan analyse {{.CLI_ARGS}}"

  test:
    deps: [ var, install ]
    cmds:
      - "{{.PHP}} vendor/bin/phpunit --colors=always {{.CLI_ARGS}}"

  proto:gen:sdk:
    desc: Generate PHP classes from proto files
    cmds:
      - rm -rf {{.SDK_GEN_DIR}}/*
      - >
        protoc -I={{.PROTO_DIR}}
        --php_out={{.SDK_GEN_DIR}}
        --php_opt=aggregate_metadata
        {{.PROTO_DIR}}/app/v1/*.proto
        {{.PROTO_DIR}}/google/api/*.proto

  proto:gen:docs:
   desc: Generate OpenApi spec
   cmds:
     - rm -rf {{.DOCS_GEN_DIR}}/*
     - >
       protoc -I={{.PROTO_DIR}}
       --openapiv2_out=logtostderr=true:{{.DOCS_GEN_DIR}}
       --openapiv2_opt=json_names_for_fields=true,allow_merge=true,merge_file_name=api
       {{.PROTO_DIR}}/app/v1/*.proto
       

  perf:test:
    deps: [ var, install ]
    cmds:
      - k6 run load-tests/scenarios/{{.CLI_ARGS | default "home.js"}}

  perf:test:all:
    deps: [ var, install ]
    cmds:
      - for f in load-tests/scenarios/*.js; do k6 run "$f"; done
