version: '3'

vars:
  PROTO_DIR: protos/proto
  SDK_GEN_DIR: protos/gen
  DOCS_GEN_DIR: docs
  PHP: php
  COMPOSER: composer

tasks:
  install:
    cmd: "{{.COMPOSER}} install"
    sources:
      - composer.json
    generates:
      - vendor/autoload.php

  var:
    cmd: mkdir -p var
    status:
      - test -d var
    silent: true
    internal: true

  fixcs:
    deps: [ var, install ]
    cmds:
      - "PHP_CS_FIXER_IGNORE_ENV=true {{.PHP}} vendor/bin/php-cs-fixer fix --verbose {{.CLI_ARGS}}"

  lint:
    cmds:
      - task: fixcs
        vars:
          CLI_ARGS: "--dry-run {{.CLI_ARGS}}"

  verify:
    deps: [ var, install, lint, phpstan, cache:clear, test ]

  phpstan:
    deps: [ var, install ]
    cmds:
      - "{{.PHP}} vendor/bin/phpstan analyse --memory-limit=256M {{.CLI_ARGS}}"

  cache:clear:
    deps: [ var, install ]
    desc: Clear application cache
    cmds:
      - "{{.PHP}} bin/cache-clear.php"

  test:
    deps: [ var, install, cache:clear ]
    cmds:
      - "{{.PHP}} vendor/bin/phpunit --colors=never {{.CLI_ARGS}}"

  proto:gen:sdk:
    desc: Generate PHP classes from proto files
    cmds:
      - rm -rf {{.SDK_GEN_DIR}}/*
      - >
        protoc -I={{.PROTO_DIR}}
        --php_out={{.SDK_GEN_DIR}}
        --php_opt=aggregate_metadata
        {{.PROTO_DIR}}/app/v1/*.proto
        {{.PROTO_DIR}}/google/api/*.proto

  proto:gen:docs:
   desc: Generate OpenApi spec
   cmds:
     - rm -rf {{.DOCS_GEN_DIR}}/*
     - >
       protoc -I={{.PROTO_DIR}}
       --openapiv2_out=logtostderr=true:{{.DOCS_GEN_DIR}}
       --openapiv2_opt=json_names_for_fields=true,allow_merge=true,merge_file_name=api
       {{.PROTO_DIR}}/app/v1/*.proto
       
  proto:gen:routes:
    desc: Generate routes from proto definitions
    deps: [ var, install ]
    cmds:
      - "{{.PHP}} bin/generate-routes.php"
      
  proto:gen:all:
    desc: Generate all artifacts from proto files
    deps: [ proto:gen:sdk, proto:gen:docs, proto:gen:routes ]

  perf:test:
    deps: [ var, install ]
    cmds:
      - k6 run load-tests/scenarios/{{.CLI_ARGS | default "home.js"}}

  perf:test:all:
    deps: [ var, install ]
    cmds:
      - for f in load-tests/scenarios/*.js; do k6 run "$f"; done
      
  services:start:
    desc: Start all application services
    cmds:
      - docker compose up -d
      - echo "Waiting for services to be ready..."
      - for i in $(seq 1 10); do
          if docker compose exec -T db-postgres pg_isready -U app >/dev/null 2>&1; then
            echo "Database is ready!";
            break;
          fi;
          echo "Services not ready yet, retrying in 1 second...";
          sleep 1;
        done
      - task: migrate
        
  migrate:
    desc: Run database migrations
    deps: [ var, install ]
    cmds:
      - "{{.PHP}} bin/migrate.php"

  services:stop:
    desc: Stop all application services
    cmds:
      - docker compose stop

  services:status:
    desc: Check the status of all application services
    cmds:
      - docker compose ps
      
  run:
    desc: Start all required services and run the application with RoadRunner
    deps: [ services:start ]
    cmds:
      - echo "Starting application with RoadRunner on http://localhost:8080..."
      - rr serve -c .rr.yaml
