<?php

declare(strict_types=1);

namespace ProtoPhpGen\Generator;

use ProtoPhpGen\Descriptor\ProtoFileDescriptor;
use ProtoPhpGen\Plugin\PluginOptions;
use ProtoPhpGen\Profile\TransportProfile;
use ProtoPhpGen\Type\TypeResolver;

final readonly class RouteManifestGenerator implements CodeGeneratorModule
{
    public const MODULE_NAME = 'route_manifest';

    public function __construct(
        private PluginOptions $options,
        private TransportProfile $transportProfile,
    ) {}

    public function getName(): string
    {
        return self::MODULE_NAME;
    }

    public function isEnabled(PluginOptions $options): bool
    {
        return $options->isModuleEnabled(self::MODULE_NAME);
    }

    /**
     * @return list<GeneratedFile>
     */
    public function generateForProtoFile(ProtoFileDescriptor $protoFile, TypeResolver $typeResolver): array
    {
        $routes = [];
        $fileNamespace = $typeResolver->resolveFileNamespace($protoFile);
        if ($fileNamespace === '') {
            return [];
        }

        foreach ($protoFile->getServices() as $service) {
            $serviceName = $service->getName();
            if ($serviceName === '') {
                continue;
            }

            $handlerNamespace = $this->transportProfile->buildServiceNamespace(
                $this->options->getNamespace(),
                $fileNamespace,
                $serviceName,
            );

            foreach ($service->getMethods() as $method) {
                $methodName = $method->getName();
                if ($methodName === '') {
                    continue;
                }

                $handlerClass = $handlerNamespace . '\\' . $methodName . 'HttpHandler';
                $operationId = $serviceName . '.' . $methodName;

                foreach ($method->getHttpBindings() as $binding) {
                    if ($binding->getMethod() === '' || $binding->getPath() === '') {
                        continue;
                    }

                    $routes[] = [
                        'method' => $binding->getMethod(),
                        'path' => $binding->getPath(),
                        'handler' => $handlerClass,
                        'operation_id' => $operationId,
                    ];
                }
            }
        }

        if ($routes === []) {
            return [];
        }

        return [
            new GeneratedFile(
                $this->buildManifestPath($protoFile),
                $this->renderManifest($routes),
            ),
        ];
    }

    private function buildManifestPath(ProtoFileDescriptor $protoFile): string
    {
        $sourceName = $protoFile->getName();
        if ($sourceName === '') {
            throw new \RuntimeException('Route manifest generation requires the source proto file name');
        }

        $normalizedSourceName = preg_replace('/\.proto$/', '.php', $sourceName);
        if (!\is_string($normalizedSourceName)) {
            throw new \RuntimeException("Unable to normalize proto file name: {$sourceName}");
        }

        return rtrim($this->options->getOutputDir(), '/')
            . '/Generated/RouteManifest/'
            . $normalizedSourceName;
    }

    /**
     * @param list<array{
     *     method: string,
     *     path: string,
     *     handler: string,
     *     operation_id: string
     * }> $routes
     */
    private function renderManifest(array $routes): string
    {
        $routesCode = var_export($routes, true);

        return <<<PHP
            <?php

            declare(strict_types=1);

            /**
             * WARNING: This file is automatically generated
             * from protobuf definitions. Do not edit manually.
             *
             * @return list<array{
             *     method: string,
             *     path: string,
             *     handler: string,
             *     operation_id: string
             * }>
             */
            return {$routesCode};

            PHP;
    }
}
