<?php

declare(strict_types=1);

namespace Tests\Unit\Generator;

use PHPUnit\Framework\TestCase;
use SqlGen\Config\GeneratorConfig;
use SqlGen\Generator\PhpQueryGenerator;
use SqlGen\Model\DatabaseSchema;
use SqlGen\Model\SchemaColumn;
use SqlGen\Model\SchemaTable;
use SqlGen\Model\SqlFile;
use SqlGen\Model\SqlParameter;
use SqlGen\Model\SqlResultKind;
use SqlGen\Model\SqlStatement;
use SqlGen\Type\PhpTypeFactory;

final class PhpQueryGeneratorTest extends TestCase
{
    public function testGeneratesRowAndQueryFiles(): void
    {
        $generator = new PhpQueryGenerator(
            new GeneratorConfig(
                inputDir: 'sql/queries',
                outputDir: 'gen/Generated/Sql',
                namespace: 'App\\Generated\\Sql',
                schemaPath: 'sql/schema.sql',
            ),
            new DatabaseSchema([
                'sessions' => new SchemaTable('sessions', [
                    'id' => new SchemaColumn('id', 'TEXT', PhpTypeFactory::fromNativeType('string'), false),
                ]),
            ]),
        );

        $files = $generator->generateForSqlFile(
            new SqlFile(
                sourcePath: 'sql/queries/session.sql',
                moduleName: 'Session',
                statements: [
                    new SqlStatement(
                        name: 'FindSessionById',
                        resultKind: SqlResultKind::One,
                        sql: 'SELECT id FROM sessions WHERE id = :id;',
                        parameters: [new SqlParameter('id')],
                    ),
                ],
            ),
        );

        self::assertCount(2, $files);
        self::assertSame('gen/Generated/Sql/Session/FindSessionByIdRow.php', $files[0]->path);
        self::assertStringContainsString('Generated by sql-gen.  DO NOT EDIT!', $files[0]->content);
        self::assertStringContainsString('source: sql/queries/session.sql', $files[0]->content);
        self::assertStringContainsString('schema: sql/schema.sql', $files[0]->content);
        self::assertStringContainsString('final readonly class FindSessionByIdRow', $files[0]->content);
        self::assertStringContainsString('implements DatabaseRow', $files[0]->content);
        self::assertStringContainsString("@implements DatabaseRow<array{'id': string}>", $files[0]->content);
        self::assertStringContainsString("@param array{'id': string} \$row", $files[0]->content);
        self::assertStringContainsString('fromDatabaseRow', $files[0]->content);
        self::assertSame('gen/Generated/Sql/Session/FindSessionByIdQuery.php', $files[1]->path);
        self::assertStringContainsString('Generated by sql-gen.  DO NOT EDIT!', $files[1]->content);
        self::assertStringContainsString('source: sql/queries/session.sql', $files[1]->content);
        self::assertStringContainsString('schema: sql/schema.sql', $files[1]->content);
        self::assertStringContainsString('implements OneRowQuery', $files[1]->content);
        self::assertStringContainsString("@implements OneRowQuery<FindSessionByIdRow, array{'id': string}>", $files[1]->content);
        self::assertStringContainsString('private string $id', $files[1]->content);
        self::assertStringContainsString('public static function create(string $id): self', $files[1]->content);
        self::assertStringContainsString('return new self(', $files[1]->content);
        self::assertStringContainsString("@return array{'id': string}", $files[1]->content);
        self::assertStringContainsString("'id' => \$this->id", $files[1]->content);
    }

    public function testSkipsEmptyParamsClassesForQueriesWithoutParameters(): void
    {
        $generator = new PhpQueryGenerator(
            new GeneratorConfig(
                inputDir: 'sql/queries',
                outputDir: 'gen/Generated/Sql',
                namespace: 'App\\Generated\\Sql',
                schemaPath: 'sql/schema.sql',
            ),
            new DatabaseSchema([
                'sessions' => new SchemaTable('sessions', [
                    'id' => new SchemaColumn('id', 'TEXT', PhpTypeFactory::fromNativeType('string'), false),
                ]),
            ]),
        );

        $files = $generator->generateForSqlFile(
            new SqlFile(
                sourcePath: 'sql/queries/session.sql',
                moduleName: 'Session',
                statements: [
                    new SqlStatement(
                        name: 'FindAllSessions',
                        resultKind: SqlResultKind::Many,
                        sql: 'SELECT id FROM sessions;',
                        parameters: [],
                    ),
                ],
            ),
        );

        self::assertCount(2, $files);
        self::assertSame('gen/Generated/Sql/Session/FindAllSessionsRow.php', $files[0]->path);
        self::assertSame('gen/Generated/Sql/Session/FindAllSessionsQuery.php', $files[1]->path);
        self::assertStringNotContainsString('private FindAllSessionsParams $params', $files[1]->content);
        self::assertStringContainsString('public static function create(): self', $files[1]->content);
        self::assertStringContainsString('return new self();', $files[1]->content);
        self::assertStringContainsString('@return array{}', $files[1]->content);
        self::assertStringContainsString('return [];', $files[1]->content);
    }

    public function testDeduplicatesEquivalentRowShapesIntoSharedModuleRow(): void
    {
        $generator = new PhpQueryGenerator(
            new GeneratorConfig(
                inputDir: 'sql/queries',
                outputDir: 'gen/Generated/Sql',
                namespace: 'App\\Generated\\Sql',
                schemaPath: 'sql/schema.sql',
            ),
            new DatabaseSchema([
                'sessions' => new SchemaTable('sessions', [
                    'id' => new SchemaColumn('id', 'TEXT', PhpTypeFactory::fromNativeType('string'), false),
                    'user_id' => new SchemaColumn('user_id', 'BIGINT', PhpTypeFactory::fromNativeType('int'), true),
                ]),
            ]),
        );

        $files = $generator->generateForSqlFile(
            new SqlFile(
                sourcePath: 'sql/queries/session.sql',
                moduleName: 'Session',
                statements: [
                    new SqlStatement(
                        name: 'FindSessionById',
                        resultKind: SqlResultKind::One,
                        sql: 'SELECT id, user_id FROM sessions WHERE id = :id;',
                        parameters: [new SqlParameter('id')],
                    ),
                    new SqlStatement(
                        name: 'FindSessionsByUserId',
                        resultKind: SqlResultKind::Many,
                        sql: 'SELECT id, user_id FROM sessions WHERE user_id = :user_id;',
                        parameters: [new SqlParameter('user_id')],
                    ),
                ],
            ),
        );

        self::assertCount(3, $files);
        self::assertSame('gen/Generated/Sql/Session/SessionRow.php', $files[0]->path);
        self::assertStringContainsString('final readonly class SessionRow', $files[0]->content);
        self::assertStringContainsString('implements DatabaseRow', $files[0]->content);
        self::assertStringContainsString("@implements DatabaseRow<array{'id': string, 'user_id': null|int}>", $files[0]->content);
        self::assertStringContainsString("@param array{'id': string, 'user_id': null|int} \$row", $files[0]->content);
        self::assertSame('gen/Generated/Sql/Session/FindSessionByIdQuery.php', $files[1]->path);
        self::assertStringContainsString('implements OneRowQuery', $files[1]->content);
        self::assertStringContainsString("@implements OneRowQuery<SessionRow, array{'id': string}>", $files[1]->content);
        self::assertStringContainsString('return SessionRow::class;', $files[1]->content);
        self::assertStringContainsString("@return array{'id': string}", $files[1]->content);
        self::assertSame('gen/Generated/Sql/Session/FindSessionsByUserIdQuery.php', $files[2]->path);
        self::assertStringContainsString('implements ManyRowsQuery', $files[2]->content);
        self::assertStringContainsString("@implements ManyRowsQuery<SessionRow, array{'user_id': null|int}>", $files[2]->content);
        self::assertStringContainsString('public static function create(?int $userId): self', $files[2]->content);
        self::assertStringContainsString('userId: $userId', $files[2]->content);
        self::assertStringContainsString("@return array{'user_id': null|int}", $files[2]->content);
        self::assertStringContainsString("'user_id' => \$this->userId", $files[2]->content);
    }

    public function testGeneratesRowsFromAliasedSelectColumns(): void
    {
        $generator = new PhpQueryGenerator(
            new GeneratorConfig(
                inputDir: 'sql/queries',
                outputDir: 'gen/Generated/Sql',
                namespace: 'App\\Generated\\Sql',
                schemaPath: 'sql/schema.sql',
            ),
            new DatabaseSchema([
                'sessions' => new SchemaTable('sessions', [
                    'id' => new SchemaColumn('id', 'TEXT', PhpTypeFactory::fromNativeType('string'), false),
                    'user_id' => new SchemaColumn('user_id', 'BIGINT', PhpTypeFactory::fromNativeType('int'), true),
                ]),
            ]),
        );

        $files = $generator->generateForSqlFile(
            new SqlFile(
                sourcePath: 'sql/queries/session.sql',
                moduleName: 'Session',
                statements: [
                    new SqlStatement(
                        name: 'FindAliasedSessions',
                        resultKind: SqlResultKind::Many,
                        sql: 'SELECT id AS session_id, user_id AS owner_id FROM sessions;',
                        parameters: [],
                    ),
                ],
            ),
        );

        self::assertCount(2, $files);
        self::assertStringContainsString("@implements DatabaseRow<array{'session_id': string, 'owner_id': null|int}>", $files[0]->content);
        self::assertStringContainsString('public string $sessionId', $files[0]->content);
        self::assertStringContainsString('public ?int $ownerId', $files[0]->content);
        self::assertStringContainsString("\$row['session_id']", $files[0]->content);
        self::assertStringContainsString("\$row['owner_id']", $files[0]->content);
    }

    public function testGeneratesQueriesAgainstCustomRuntimeNamespace(): void
    {
        $generator = new PhpQueryGenerator(
            new GeneratorConfig(
                inputDir: 'sql/queries',
                outputDir: 'gen/Generated/Sql',
                namespace: 'Vendor\\Custom\\Sql',
                schemaPath: 'sql/schema.sql',
                profile: \SqlGen\Config\SqlGenerationProfile::withRuntimeNamespace('Vendor\\Runtime\\Sql'),
            ),
            new DatabaseSchema([
                'sessions' => new SchemaTable('sessions', [
                    'id' => new SchemaColumn('id', 'TEXT', PhpTypeFactory::fromNativeType('string'), false),
                ]),
            ]),
        );

        $files = $generator->generateForSqlFile(
            new SqlFile(
                sourcePath: 'sql/queries/session.sql',
                moduleName: 'Session',
                statements: [
                    new SqlStatement(
                        name: 'FindSessionById',
                        resultKind: SqlResultKind::One,
                        sql: 'SELECT id FROM sessions WHERE id = :id;',
                        parameters: [new SqlParameter('id')],
                    ),
                ],
            ),
        );

        self::assertStringContainsString('use Vendor\\Runtime\\Sql\\DatabaseRow;', $files[0]->content);
        self::assertStringContainsString('implements DatabaseRow', $files[0]->content);
        self::assertStringContainsString('use Vendor\\Runtime\\Sql\\ExecutableQuery;', $files[1]->content);
        self::assertStringContainsString('use Vendor\\Runtime\\Sql\\OneRowQuery;', $files[1]->content);
        self::assertStringContainsString('implements OneRowQuery', $files[1]->content);
    }
}
