<?php

declare(strict_types=1);

use App\Platform\Http\Handler\HandlerInterface;

/**
 * WARNING: This file is automatically generated
 * from protobuf definitions. Do not edit manually.
 *
 * @return array<array{
 *     method: string,
 *     path: string,
 *     handler: class-string<HandlerInterface>
 * }>
 */
return [

];
