<?php

declare(strict_types=1);

use App\Generated\Transport\Api\V1\HealthService\CheckHttpHandler;
use App\Platform\Http\Handler\HandlerInterface;

/**
 * WARNING: This file is automatically generated
 * from protobuf definitions. Do not edit manually.
 *
 * @return array<array{
 *     method: string,
 *     path: string,
 *     handler: class-string<HandlerInterface>
 * }>
 */
return [
    // HealthService.Check
    [
        'method' => 'GET',
        'path' => '/api/v1/health',
        'handler' => CheckHttpHandler::class,
    ],
];
