name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build Release Package
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, sqlite3
          coverage: none
          tools: composer:v2
      
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader
      
      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          
      - name: Install protoc-gen-openapiv2
        run: |
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.18.0
          echo "PATH=$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV
          # Copy plugin to a location where Docker can access it
          sudo cp $(go env GOPATH)/bin/protoc-gen-openapiv2 /usr/local/bin/
      
      - name: Generate proto artifacts
        run: |
          # Create necessary directories
          mkdir -p protos/gen docs
          
          # Pull and use appropriate protobuf Docker image
          echo "Generating PHP SDK..."
          docker run --rm -v $(pwd):/workspace -v /usr/local/bin/protoc-gen-openapiv2:/usr/local/bin/protoc-gen-openapiv2 \
            jaegertracing/protobuf:0.4.0 \
            protoc -I=/workspace/protos/proto \
            --php_out=/workspace/protos/gen \
            --php_opt=aggregate_metadata \
            /workspace/protos/proto/app/v1/*.proto \
            /workspace/protos/proto/google/api/*.proto
          
          echo "Generating OpenAPI docs..."
          docker run --rm -v $(pwd):/workspace -v /usr/local/bin/protoc-gen-openapiv2:/usr/local/bin/protoc-gen-openapiv2 \
            jaegertracing/protobuf:0.4.0 \
            protoc -I=/workspace/protos/proto \
            --openapiv2_out=logtostderr=true:/workspace/docs \
            --openapiv2_opt=json_names_for_fields=true,allow_merge=true,merge_file_name=api \
            /workspace/protos/proto/app/v1/*.proto
          
          echo "Generating routes..."
          PHP_CS_FIXER_IGNORE_ENV=true php bin/generate-routes.php
          
          # Fix permissions
          sudo chown -R $(id -u):$(id -g) protos/gen docs
      
      - name: Prepare release assets
        run: |
          # Create release directory
          mkdir -p release_assets
          
          # Package application
          tar -czf release_assets/api-template-${{ github.event.release.tag_name }}.tar.gz \
            --exclude='.git*' \
            --exclude='tests' \
            --exclude='var' \
            --exclude='load-tests' \
            --exclude='taskfile.yaml' \
            .
          
          # Copy OpenAPI docs
          cp ./docs/api.swagger.json release_assets/api-swagger-${{ github.event.release.tag_name }}.json
      
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release_assets/api-template-${{ github.event.release.tag_name }}.tar.gz
            release_assets/api-swagger-${{ github.event.release.tag_name }}.json
          token: ${{ secrets.GITHUB_TOKEN }}