name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build Release Package
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, intl, sqlite3
          coverage: none
          tools: composer:v2
      
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader
      
      - name: Install Taskfile
        uses: arduino/setup-task@v1
        with:
          version: '3.x'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install Protoc
        run: |
          PROTOC_VERSION="3.20.0"
          PROTOC_ZIP="protoc-${PROTOC_VERSION}-linux-x86_64.zip"
          curl -OL "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/${PROTOC_ZIP}"
          sudo unzip -o "${PROTOC_ZIP}" -d /usr/local bin/protoc
          sudo unzip -o "${PROTOC_ZIP}" -d /usr/local include/*
          rm -f "${PROTOC_ZIP}"
      
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          
      - name: Install protoc-gen-openapiv2
        run: |
          go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.18.0
          echo "PATH=$PATH:$(go env GOPATH)/bin" >> $GITHUB_ENV
      
      - name: Generate proto artifacts
        run: PHP_CS_FIXER_IGNORE_ENV=true task proto:gen:all
      
      - name: Prepare release assets
        run: |
          # Create release directory
          mkdir -p release_assets
          
          # Package application
          tar -czf release_assets/api-template-${{ github.event.release.tag_name }}.tar.gz \
            --exclude='.git*' \
            --exclude='tests' \
            --exclude='var' \
            --exclude='load-tests' \
            --exclude='taskfile.yaml' \
            .
          
          # Copy OpenAPI docs
          cp ./docs/api.swagger.json release_assets/api-swagger-${{ github.event.release.tag_name }}.json
      
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release_assets/api-template-${{ github.event.release.tag_name }}.tar.gz
            release_assets/api-swagger-${{ github.event.release.tag_name }}.json
          token: ${{ secrets.GITHUB_TOKEN }}